# Generated by Django 2.1.7 on 2019-04-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmen', models.CharField(max_length=5)),
                ('undulating', models.IntegerField()),
                ('porthole', models.IntegerField()),
                ('mainroad', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('drainage', models.IntegerField()),
                ('bundwall', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('RCI', models.FloatField()),
            ],
        ),
    ]
