# Generated by Django 2.1.7 on 2019-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklamasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=5)),
                ('luas', models.FloatField()),
                ('tanaman_utama', models.CharField(max_length=24)),
                ('status', models.CharField(max_length=24)),
            ],
        ),
    ]
