# Generated by Django 2.1.7 on 2019-04-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcihauling',
            old_name='potholeo',
            new_name='porthole',
        ),
        migrations.AlterModelTable(
            name='allbor',
            table=None,
        ),
    ]
